DividaBill SysOp/Controllers/ReferalsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DividaBill.Models;
using DividaBill.DAL;

namespace DividaBill.SysOp.Controllers
{
    public class ReferalsController : AdminController
    {

        // GET: Admin/Referals
        public ActionResult Index()
        {
            return View(unitOfWork.ReferalRepository.Get().ToList());
        }

        // GET: Admin/Referals/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ReferalCode code = unitOfWork.ReferalRepository.GetByID(id);
            if (code == null)
            {
                return HttpNotFound();
            }
            return View(code);
        }

        // GET: Admin/Referals/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Referals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Code,Text")] ReferalCode code)
        {
            if (ModelState.IsValid)
            {
                unitOfWork.ReferalRepository.Insert(code);
                unitOfWork.Save();
                return RedirectToAction("Index");
            }

            return View(code);
        }

        // GET: Admin/Referals/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ReferalCode code = unitOfWork.ReferalRepository.GetByID(id);
            if (code == null)
            {
                return HttpNotFound();
            }
            return View(code);
        }

        // POST: Admin/Referals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ReferalCode code)
        {
            if (ModelState.IsValid)
            {
                unitOfWork.ReferalRepository.Update(code);
                unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(code);
        }

        // GET: Admin/Referals/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ReferalCode code = unitOfWork.ReferalRepository.GetByID(id);
            if (code == null)
            {
                return HttpNotFound();
            }
            return View(code);
        }

        // POST: Admin/Referals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ReferalCode code = unitOfWork.ReferalRepository.GetByID(id);
            unitOfWork.ReferalRepository.Delete(code);
            unitOfWork.Save();
            return RedirectToAction("Index");
        }
    }
}

DividaBill SysOp/Views/Referals/Create.cshtml
@model DividaBill.Models.ReferalCode

@{
    ViewBag.Title = "Create";
    var referals = ViewBag.Referals as IEnumerable<SelectListItem>;
    var codes = ViewBag.Codes as IEnumerable<SelectListItem>;
}



<!-- BEGIN PAGE CONTENT-->

<div class="row">

    <div class="col-md-12">

        @using (Html.BeginForm("Create", "Referals", FormMethod.Post, new { @class = "form-horizontal form-row-seperated", role = "form" }))
        {
            @Html.AntiForgeryToken()

            <div class="portlet">

                <div class="portlet-title">

                    <div class="caption">

                        <i class="fa fa-plus"></i>New Bill

                    </div>

                    <div class="actions btn-set">

                        <a href="@Url.Action("Index")" class="btn default"><i class="fa fa-angle-left"></i> Back</a>
                        <a href="@Request.Url.PathAndQuery" class="btn default"><i class="fa fa-reply"></i> Reset</a>
                        <button type="submit" class="btn green"><i class="fa fa-check"></i> Save</button>

                        @*<button class="btn green"><i class="fa fa-check-circle"></i> Save & Continue Get</button>*@

                        @*<div class="btn-group">

                                <a class="btn yellow" href="#" data-toggle="dropdown">

                                    <i class="fa fa-share"></i> More <i class="fa fa-angle-down"></i>

                                </a>

                                <ul class="dropdown-menu pull-right">

                                    <li>

                                        <a href="#">

                                            Duplicate

                                        </a>

                                    </li>

                                    <li>

                                        <a href="#">

                                            Delete

                                        </a>

                                    </li>

                                    <li class="divider">

                                    </li>

                                    <li>

                                        <a href="#">

                                            Print

                                        </a>

                                    </li>

                                </ul>

                            </div>*@

                    </div>

                </div>

                <div class="portlet-body">

                    <div class="tabbable">

                        <ul class="nav nav-tabs">

                            <li class="active">

                                <a href="#tab_general" data-toggle="tab">

                                    General

                                </a>

                            </li>


                        </ul>

                        <div class="tab-content no-space">

                            <div class="tab-pane active" id="tab_general">

                                <div class="form-body">

                                    @Html.ValidationSummary(false, "", new { @class = "text-danger" })


                                    <div class="form-group">
                                        @Html.Label("Referal", htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.DropDownListFor(model => model.Owner, referals, "--Select--", (ViewBag.DisabledDropdownList != null) ? new { @readonly = true } : null)
                                            @Html.ValidationMessage("Referal", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.Label("Code", htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.DropDownListFor(model => model.DiscountCode, referals, "--Select--", (ViewBag.DisabledDropdownList != null) ? new { @readonly = true } : null)
                                            @Html.ValidationMessage("Code", new { @class = "text-danger" })
                                        </div>
                                    </div>


                                </div>

                            </div>

                        </div>

                    </div>

                </div>

            </div>
        }
    </div>

</div>

<!-- END PAGE CONTENT-->



<div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/themes/base/css")
}

DividaBill SysOp/Views/Referals/Delete.cshtml
@model DividaBill.Models.Coupon

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Coupon</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DividaBill SysOp/Views/Referals/Details.cshtml
@model DividaBill.Models.Coupon

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Coupon</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Get", "Get", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DividaBill SysOp/Views/Referals/Edit.cshtml
@model DividaBill.Models.Coupon

@{
    ViewBag.Title = "Get";
}

<h2>Get</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Coupon</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DividaBill SysOp/Views/Referals/Index.cshtml
@model IEnumerable<DividaBill.Models.Coupon>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Text)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Code)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Text)
        </td>
        <td>
            @Html.ActionLink("Get", "Get", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>