DividaBill SysOp/Controllers/TenanciesController.cs
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;
using DividaBill.Models;
using DividaBill.Services.Exceptions;
using DividaBill.Services.Factories;
using DividaBill.Services.Interfaces;
using DividaBill.ViewModels;

namespace DividaBill.SysOp.Controllers
{
    public class TenanciesController : Controller
    {
        public readonly IEntityToViewModelMappingFactory<Tenancy, TenancyViewModel> _entityToViewModelFactory;
        private readonly IHouseService _houseService;
        private readonly ITenancyService _tenancyService;
        private readonly ITenantService _tenantService;
        public readonly IViewModelToEntityMappingFactory<TenancyViewModel, Tenancy> _viewModelToEntityFactory;

        // GET: Tenancy
        public TenanciesController(ITenancyService tenancyService, IHouseService houseService,
            IEntityToViewModelMappingFactory<Tenancy, TenancyViewModel> entityToViewModelFactory,
            IViewModelToEntityMappingFactory<TenancyViewModel, Tenancy> viewModelToEntityMapping,
            ITenantService tenantService)
        {
            _tenantService = tenantService;
            _houseService = houseService;
            _viewModelToEntityFactory = viewModelToEntityMapping;
            _entityToViewModelFactory = entityToViewModelFactory;
            _tenancyService = tenancyService;
        }


        public ActionResult GetTenancies(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            try
            {
                var tenanciesList = _tenancyService.GetTenanciesbyUserId(id);
                if (tenanciesList.Count == 0)
                {
                    ViewBag.noTenancy = "There is no tenancy for this tenant";
                    return View("~/Views/Tenancies/_TenanciesDetails.cshtml");
                }

                var viewModelList = new List<TenancyViewModel>();
                var viewModel = new TenancyViewModel();

                foreach (var tenancy in tenanciesList)
                {
                    viewModel = _entityToViewModelFactory.Map(tenancy);
                    viewModelList.Add(viewModel);
                }

                return View("~/Views/Tenancies/_TenanciesDetails.cshtml", viewModelList);
            }
            catch (TenancyNotFoundException)
            {
                return HttpNotFound();
            }
        }


        public ActionResult Edit(int tenancyId)
        {
            var entity = _tenancyService.GetTenancy(tenancyId);
            var viewModel = _entityToViewModelFactory.Map(entity);

            ViewBag.Houses = ActiveHouseList();

            return View("Edit", viewModel);
        }

        [HttpPost]
        public ActionResult Edit(TenancyViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var currentTenancy = _tenancyService.GetTenancy(viewModel.TenancyId);
                currentTenancy.JoiningDate = viewModel.JoiningDate;
                currentTenancy.LeavingDate = viewModel.LeavingDate;
                currentTenancy.Notes = viewModel.Notes;

                _tenancyService.UpdateTenancy(currentTenancy);
            }
            return RedirectToAction("Edit", "Tenants", new {id = viewModel.UserId});
        }


        public ActionResult Create(string id)
        {
            if (id != null)
            {
                var user = _tenantService.GetTenant(id);
                var viewModel = new TenancyViewModel
                {
                    UserId = id,
                    User = user
                };

                ViewBag.Houses = ActiveHouseList();

                return View("Create", viewModel);
            }
            return View("/Views/Tenants/All.cshtml");
        }

        [HttpPost]
        public ActionResult Create(TenancyViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var entity = _viewModelToEntityFactory.Map(viewModel);
                _tenancyService.CreateTenancy(entity);
            }

            return RedirectToAction("Edit", "Tenants", new {id = viewModel.UserId});
        }


        public SelectList ActiveHouseList()
        {
            var houseList = _houseService.GetAllHouses();
            return new SelectList(houseList, "ID", "houseDisplay");
        }
    }
}

DividaBill SysOp/Views/Tenancies/Create.cshtml
@model DividaBill.ViewModels.TenancyViewModel

@{
    ViewBag.Title = "Create tenancy";
    var housesList = ViewBag.Houses as IEnumerable<SelectListItem>;
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Create new tenancy for @Model.User.FullName </h4>

        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        @Html.HiddenFor(m => m.UserId)
        <div class="form-group">
            @Html.LabelFor(model => model.HouseId, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.HouseId, housesList, "Select house", new {htmlAttributes = new {@class = "form-control select2" } })
                @Html.ValidationMessageFor(model => model.HouseId, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JoiningDate, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.JoiningDate, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.JoiningDate, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LeavingDate, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.LeavingDate, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.LeavingDate, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Notes, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Notes, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default"/>
            </div>
        </div>

    </div>
    <div>
        <a href="@Url.Action("Edit", "Tenants", new { id = @Model.UserId})">Back to tenant edit</a>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/ajax")
    @Scripts.Render("~/bundles/select2")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/editHouse")
    @Styles.Render("~/Content/metronic-profile")

}

DividaBill SysOp/Views/Tenancies/Edit.cshtml
@model DividaBill.ViewModels.TenancyViewModel
@{
    ViewBag.Title = "Edit tenancy";
    var housesList = ViewBag.Houses as IEnumerable<SelectListItem>;
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Edit Tenancy @Model.TenancyId for @Model.User.FullName </h4>
        @Html.HiddenFor(m => m.UserId)
        @Html.HiddenFor(m => m.TenancyId)
        @Html.HiddenFor(m => m.HouseId)
        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})

        <div class="form-group">
            <label class="control-label col-md-2">Tenancy</label>
            <div class="col-md-10">
                @Html.DisplayFor(model => model.HouseModel.houseDisplay, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.HouseId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JoiningDate, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.JQueryUI().DatepickerFor(model => model.JoiningDate, new {htmlAttributes = new {@class = "form-control datepicker", @type = "date"}})
                @Html.ValidationMessageFor(model => model.JoiningDate, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LeavingDate, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.JQueryUI().DatepickerFor(model => model.LeavingDate, new {htmlAttributes = new {@class = "form-control datepicker"}})
                @Html.ValidationMessageFor(model => model.LeavingDate, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Notes, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Notes, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default"/>
            </div>
        </div>

    </div>
    <div>
        <a href="@Url.Action("Edit", "Tenants", new { id = @Model.UserId})">Back to tenant edit</a>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/ajax")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/select2")
    @Scripts.Render("~/bundles/editHouse")
    @Styles.Render("~/Content/metronic-profile")
<script>
        $(function () {
            checkSupportForInputTypeDate();
            $('.datepicker').datepicker({
                weekStart: 1,
                calendarWeeks: false,
                autoclose: true,
                todayBtn: true
            });
        });

       
        //Function to configure date format as the native date type from chrome and safari browsers clashes with jQuery ui date picker.
        function checkSupportForInputTypeDate() {
            jQuery.validator.methods.date = function (value, element) {
                var isChrome = /Chrome/.test(navigator.userAgent) && /Google Inc/.test(navigator.vendor);
                var isSafari = /Safari/.test(navigator.userAgent) && /Apple Computer/.test(navigator.vendor);
                if (isSafari || isChrome) {
                    var d = new Date();
                    return this.optional(element) || !/Invalid|NaN/.test(new Date(d.toLocaleDateString(value)));
                } else {
                    return this.optional(element) || !/Invalid|NaN/.test(new Date(value));
                }
            }
        }
</script>
}

DividaBill SysOp/Views/Tenancies/_TenanciesDetails.cshtml
@model IEnumerable<DividaBill.ViewModels.TenancyViewModel>

@{
    Layout = "";
    var noTenancy = ViewBag.noTenancy;
}

<br />
<br/>
@if (@noTenancy == null)
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TenancyId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserId)
            </th>
            <th>
                House Id
            </th>
            <th>
                Address
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JoiningDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LeavingDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Notes)
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TenancyId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserId)
                </td>
                <td>
                    <a href="~/Houses/Details/@item.HouseId">@item.HouseId</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HouseModel.houseDisplay)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.JoiningDate, new {@class = "datepicker"})
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LeavingDate, new {@class = "datepicker"})
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Notes)
                </td>
                <td>
                    <a href="@Url.Action("Edit", "Tenancies", new {item.TenancyId})" target="_blank">Edit</a>
                </td>
            </tr>
        }
    </table>
}
else
{
    <div>@noTenancy</div>
}

DividaBill SysOp/Views/Tenancies/_TenanciesEdit.cshtml
@model DividaBill.ViewModels.TenancyViewModel

@{
    Layout = "";
    var housesList = ViewBag.Houses as IEnumerable<SelectListItem>;
}

<style>
    .display_date {
        float: right;
        margin-left: 30px;
    }

    .tenancy-row { width: 1000px; }

    .input-line {
        float: left;
        width: 550px;
    }

    .modal-content, .modal-dialog {
        background-color: white;
        width: 1500px;
    }

</style>

<div class="">

    @using (Html.BeginForm("Edit", "Tenancies", null, FormMethod.Post, new {@id = "form-tenancy-edit", @class = "form-horizontal form-row-seperated"}))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(m => m.TenancyId)
        @Html.HiddenFor(m => m.UserId)

        <div class="form-group">
            <div class="col-md-10">
                <br/>
                <div class="portlet">
                </div>
                <div class="row">
                    <div class="form-group">
                        @Html.Label("Current house: ", new { @class = "control-label col-md-2" })
                        <div class="col-md-4 tenancy-row" style="width: 1000px">
                            @if (ViewBag.currentHouse != null)
                            {
                                @ViewBag.currentHouse
                                <span class="display_date">
                                    <strong>@Html.LabelFor(m => m.LeavingDate) </strong>
                                    @Html.JQueryUI().DatepickerFor(m => m.LeavingDate, new {htmlAttributes = new {@class = "form-control"}})
                                </span>
                            }
                            else
                            {
                                @ViewBag.noTenancy
                            }
                        </div>
                        </div>
                    </div>
                    <br />
                    <br />
                    <br />
                <div class="row">
                    <div class="form-group">
                        @Html.Label("Move to new house: ", new { @class = "control-label col-md-2" })
                        <div class="col-md-4 tenancy-row">
                            @Html.DropDownListFor(m => m.HouseId, housesList, "Select house", new { @id = "HouseDropDown", @class = "select2me form-control input-line"})
                            <span class="display_date">
                                <strong>@Html.LabelFor(m => m.JoiningDate) </strong>
                                @Html.JQueryUI().DatepickerFor(m => m.JoiningDate, new {htmlAttributes = new {@class = "form-control"}})
                            </span>
                        </div>
                    </div>
                </div>
           </div>
        </div>
    }
</div>