Dividabill-Jemal/Areas/Admin/Controllers/BillsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Dividabill.Models;
using Dividabill.Areas.Admin.ViewModels;
using Dividabill.Helpers;
using Dividabill.Services;
using Dividabill.DAL;

namespace Dividabill.Areas.Admin.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class BillsController : AdminController
    {
        // GET: Admin/Bills
        public ActionResult Index(string id)
        {
            DateTime parsedSelectedTime = DateTime.Now;
            if (!DateTime.TryParse(id, out parsedSelectedTime))
            {
                parsedSelectedTime = DateTime.Now;
            }
            DateTime selectedMonthBegins = new DateTime(parsedSelectedTime.Year, parsedSelectedTime.Month, 1);
            DateTime selectedMonthEnds = selectedMonthBegins.AddMonths(1);

            //Define Bills list
            List<BillsViewModel> selectedBills = new List<BillsViewModel>();

            //Get the bills for the selected month
            List<Bill> bills = unitOfWork.BillRepository.Get(p => p.StartDate >= selectedMonthBegins && p.EndDate < selectedMonthEnds).ToList();

            foreach (Bill bill in bills)
            {
                selectedBills.Add(new BillsViewModel { House = bill.House, ElectricBill = bill.ElectricBill, GasBill = bill.GasBill, WaterBill = bill.WaterBill, Note = bill.Note, Adjustment = bill.Adjustment, BillID = bill.Id, ServiceCharge = bill.DeliveryFee });
            }
            return View(selectedBills);
        }

        // GET: Admin/Bills/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bill bill = unitOfWork.BillRepository.GetByID(id);
            if (bill == null)
            {
                return HttpNotFound();
            }
            return View(bill);
        }

        // GET: Admin/Bills/Create
        public ActionResult Create()
        {

            var bill = new Bill();
            bill.Month = DateTime.Now;
            ViewBag.Houses = new SelectList(unitOfWork.ActiveHouses.Get(h => !h.Archived && (h.EndDate > DateTime.Now)).ToList(), "ID", "Address.Line1");
            return View(bill);
        }

        [RequireRequestValue("houseId")]
        public ActionResult Create(int houseId)
        {

            HouseModel house = unitOfWork.ActiveHouses.GetByID(houseId);
            if (house == null)
            {
                return HttpNotFound();
            }
            var bill = new Bill();
            bill.HouseModelID = houseId;
            bill.Month = DateTime.Now;
            ViewBag.Houses = new SelectList(unitOfWork.ActiveHouses.Get(h => !h.Archived && (h.EndDate > DateTime.Now)).ToList(), "ID", "Address.Line1");
            ViewBag.DisabledDropdownList = true;
            return View(bill);
        }

        // POST: Admin/Bills/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Bill mbill)
        {
            //if (bill.House == null)
            //{
            //    ModelState.AddModelError("House", "The house can't be empty.");
            //}
            if (ModelState.IsValid)
            {
                if (mbill.Type == BillType.Estimated)
                {
                    BillService _service = new BillService(unitOfWork);
                    _service.GenerateEstimatedBill(mbill.StartDate, mbill.EndDate, mbill.HouseModelID);
                }
                else
                {
                    unitOfWork.BillRepository.Insert(mbill);
                    unitOfWork.Save();
                }
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Houses = new SelectList(unitOfWork.ActiveHouses.Get(h => !h.Archived && (h.EndDate > DateTime.Now)).ToList(), "ID", "Address.Street");
            }

            return View(mbill);
        }

        // GET: Admin/Bills/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bill bill = unitOfWork.BillRepository.GetByID(id);
            if (bill == null)
            {
                return HttpNotFound();
            }
            ViewBag.Houses = new SelectList(unitOfWork.ActiveHouses.Get(h => !h.Archived && (h.EndDate > DateTime.Now)).ToList(), "ID", "Address.Line1");
            return View(bill);
        }

        // POST: Admin/Bills/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ElectricBill,GasBill,WaterBill,Month,HouseModelID,Adjustment,Note,Status")] Bill bill)
        {
            if (ModelState.IsValid)
            {
                unitOfWork.BillRepository.Update(bill);
                unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(bill);
        }

        // GET: Admin/Bills/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bill bill = unitOfWork.BillRepository.GetByID(id);
            if (bill == null)
            {
                return HttpNotFound();
            }
            return View(bill);
        }

        // POST: Admin/Bills/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Bill bill = unitOfWork.BillRepository.GetByID(id);
            unitOfWork.BillRepository.Delete(bill);
            unitOfWork.Save();
            return RedirectToAction("Index");
        }
    }
}

Dividabill-Jemal/Areas/Admin/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Dividabill.Models;
using System.Web.UI;
using System.IO;
using System.Web.UI.WebControls;
using Dividabill.DAL;
using System.Text;
using System.Reflection;
using System.Data.SqlTypes;

namespace Dividabill.Areas.Admin.Controllers
{
    public class UsersController : AdminController
    {
        // GET: Admin/Users
        public ActionResult Index()
        {
            return All();
        }

        // GET: Admin/Users/Active
        public ActionResult Active()
        {
            return View("Index", unitOfWork.UserRepository.GetActiveClients().ToList());
        }
        
        // GET: Admin/Users/All
        public ActionResult All()
        {
            return View("Index", unitOfWork.UserRepository.Get().ToList());
        }

        // GET: Admin/Users/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = unitOfWork.UserRepository.GetByID(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Admin/Users/Create
        public ActionResult Create()
        {

            ViewBag.Houses = new SelectList(unitOfWork.ActiveHouses.GetHouses().ToList(), "ID", "Address.Line1");

            return View();
        }

        // POST: Admin/Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,RefTitle,FirstName,LastName,AccountNumber,AccountSortCode,AccountHolder,AccountSoleHolder,DOB,HomeAddress,Note,NewsletterSubscription,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] User user)
        {
            user.UserName = user.Email;
            if (ModelState.IsValid)
            {
                unitOfWork.UserRepository.Insert(user);
                unitOfWork.Save();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: Admin/Users/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = unitOfWork.UserRepository.GetByID(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            ViewBag.Houses = new SelectList(unitOfWork.ActiveHouses.GetHouses().ToList(), "ID", "Address.Line1");
            return View(user);
        }

        // POST: Admin/Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,RefTitle,FirstName,LastName,AccountNumber,AccountSortCode,AccountHolder,AccountSoleHolder,DOB,HomeAddress,Note,NewsletterSubscription,Email,PhoneNumber,House_ID,DDRef")] User user)
        {
            if (ModelState.IsValid)
            {
                if (user.SignupDate == DateTime.MinValue)
                {
                    user.SignupDate = SqlDateTime.MinValue.Value;
                }
                user.UserName = user.Email;
                unitOfWork.UserRepository.Update(user);
                unitOfWork.Save();

                return RedirectToAction("Index");
            } 
            ViewBag.Houses = new SelectList(unitOfWork.ActiveHouses.GetHouses().ToList(), "ID", "Address.Line1");

            return View(user);
        }

        // GET: Admin/Users/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = unitOfWork.UserRepository.GetByID(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Admin/Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            unitOfWork.UserRepository.Delete(id);
            unitOfWork.Save();

            return RedirectToAction("Index");
        }


        public ActionResult Export(string FileType = "Excel", string Type = "Clients", int days = 100, int houseID = 0)
        {

            var clients = new System.Data.DataTable("Clients");

            clients.Columns.Add("Id", typeof(string));
            clients.Columns.Add("Email", typeof(string));
            clients.Columns.Add("Title", typeof(string));
            clients.Columns.Add("FirstName", typeof(string));
            clients.Columns.Add("LastName", typeof(string));
            clients.Columns.Add("AccountNumber", typeof(string));
            clients.Columns.Add("AccountSortCode", typeof(string));
            clients.Columns.Add("AccountHolder", typeof(string));
            clients.Columns.Add("AccountSoleHolder", typeof(bool));
            clients.Columns.Add("DOB", typeof(DateTime));
            clients.Columns.Add("HomeAddress", typeof(string));
            clients.Columns.Add("PhoneNumber", typeof(string));

            //House addin
            if (houseID != 0)
            {

                clients.Columns.Add("Housemates", typeof(int));
                clients.Columns.Add("Address", typeof(string));
                clients.Columns.Add("Electricity", typeof(bool));
                clients.Columns.Add("Gas", typeof(bool));
                clients.Columns.Add("Water", typeof(bool));
                clients.Columns.Add("Media", typeof(bool));
                clients.Columns.Add("StartDate", typeof(DateTime));
                clients.Columns.Add("EndDate", typeof(DateTime));
                clients.Columns.Add("RegisteredDate", typeof(DateTime));
                clients.Columns.Add("Coupon", typeof(string));
            }

            List<User> dbClients;
            switch (Type)
            {
                default:
                    dbClients = unitOfWork.UserRepository.GetActiveClients().ToList();
                    break;
            }
            if (houseID != 0)
            {
                dbClients = dbClients.Where(u => u.House_ID == houseID).ToList();
            }
            foreach (User client in dbClients)
            {
                if (houseID != 0)
                {

                    clients.Rows.Add(client.Id, client.Email, client.RefTitle, client.FirstName, client.LastName, client.AccountNumber,
                        client.AccountSortCode, client.AccountHolder, client.AccountSoleHolder, client.DOB, client.HomeAddress,
                        client.PhoneNumber, client.House.Housemates, client.House.Address, client.House.Electricity, client.House.Gas,
                        client.House.Water, client.House.Media, client.House.StartDate.Date, client.House.EndDate.Date, client.House.RegisteredDate.Date,
                        (client.House.Coupon != null) ? client.House.Coupon.Code : "");
                }
                else
                {
                    clients.Rows.Add(client.House.ID, client.Email, client.RefTitle, client.FirstName, client.LastName, client.AccountNumber,
                        client.AccountSortCode, client.AccountHolder, client.AccountSoleHolder, client.DOB, client.HomeAddress, client.PhoneNumber);
                }
            }


            var grid = new GridView();
            grid.DataSource = clients;
            grid.DataBind();

            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=Clients.xls");
            Response.ContentType = "application/ms-excel";
            Response.Charset = "";
            StringWriter sw = new StringWriter();
            HtmlTextWriter htw = new HtmlTextWriter(sw);
            grid.RenderControl(htw);
            Response.Output.Write(sw.ToString());
            Response.Flush();
            Response.End();

            return RedirectToAction("Index");
        }
        public ActionResult Export2(string FileType = "Excel", string Type = "Clients", int days = 100, int houseID = 0)
        {


            List<User> dbClients = unitOfWork.UserRepository.GetActiveClients().Where(u => u.DDRef == null || u.DDRef.StartsWith("DBILL") == false).ToList();
            List<EazyCollectPerson> eazycollect = new List<EazyCollectPerson>();
            int i=0;
            foreach (User client in dbClients)
            {
                i++;
                client.DDRef = i.ToString();
                //unitOfWork.Save();
                eazycollect.Add(
                    new EazyCollectPerson
                    {
                        contract = new Contract
                        {
                            IsGiftAid = false,
                            PaymentDayInMonth = "1",
                            Start = "01/11/2014",
                            Every = "1"
                        },
                        customer = new Customer
                        {
                            FirstName = client.FirstName,
                            Surname = client.LastName,
                            DateOfBirth = client.DOB.ToShortDateString(),

Dividabill-Jemal/Areas/Admin/Views/Houses/Details.cshtml
@model Dividabill.Models.HouseModel

@{
    ViewBag.Title = "Details";
    var address = @Model.Address.ToString();
}

<div class="row profile">

    <div class="col-md-12">

        <!--BEGIN TABS-->

        <div class="tabbable tabbable-custom tabbable-full-width">
            <ul class="nav nav-tabs">
                <li class="active"><a href="#tab_1_1" data-toggle="tab">Overview</a></li>
                <li><a href="#tab_1_6" data-toggle="tab">Tenants</a></li>
            </ul>

            <div class="tab-content">

                <div class="tab-pane active" id="tab_1_1">

                    <div class="row">

                        <div class="col-md-3">

                            <ul class="list-unstyled profile-nav">
                                <li><img src="http://maps.googleapis.com/maps/api/streetview?size=400x400&location=@{@address}" class="img-responsive" alt="" /></li>
                                <li>@Html.ActionLink("Add Bill", "Create", "Bills", new { houseId = Model.ID }, null)</li>
                                <li><a href="#">Messages<span>3</span></a></li>
                                <li>@Html.ActionLink("Export to Excel", "Export", "Users", new {  id = "Excel", includeHouse = true, houseID = Model.ID }, null)</li>
                                <li>@Html.ActionLink("Send BG Email", "SendBGEmail", new { id = Model.ID })</li>
                                <li>@Html.ActionLink("Generate BG Form", "GenerateBGForm", new { id = Model.ID })</li>
                                <li>@Html.ActionLink("Edit", "Edit", new { id = Model.ID })</li>
                            </ul>

                        </div>

                        <div class="col-md-9">

                            <div class="row">

                                <div class="col-md-8 profile-info">

                                    <h1>House @Model.ID</h1>

                                    <p>@Model.Note</p>

                                    <ul class="list-inline">
                                        <li><i class="fa fa-map-marker"></i> @address</li>
                                        <li><i class="fa fa-calendar"></i> @Model.StartDate.ToShortDateString() - @Model.EndDate.ToShortDateString()</li>
                                        <li><i class="fa fa-users"></i> @Model.Tenants.Count()/@Model.Housemates</li>
                                    </ul>

                                </div>

                                <!--end col-md-8-->

                                <div class="col-md-4">

                                    <div class="portlet sale-summary">

                                        <div class="portlet-title">
                                            <div class="caption">Subscriptions</div>
                                        </div>

                                        <div class="portlet-body">

                                            <ul class="list-unstyled">

                                                <li>

                                                    <span class="sale-info">

                                                        @Html.DisplayNameFor(model => model.Electricity)

                                                    </span>

                                                    <span class="sale-num">

                                                        @Html.DisplayFor(model => model.Electricity)

                                                    </span>

                                                </li>

                                                <li>

                                                    <span class="sale-info">

                                                        @Html.DisplayNameFor(model => model.Gas)

                                                    </span>

                                                    <span class="sale-num">

                                                        @Html.DisplayFor(model => model.Gas)

                                                    </span>

                                                </li>

                                                <li>

                                                    <span class="sale-info">

                                                        @Html.DisplayNameFor(model => model.Water)

                                                    </span>

                                                    <span class="sale-num">@Html.DisplayFor(model => model.Water)</span>

                                                </li>

                                                <li>

                                                    <span class="sale-info">

                                                        @Html.DisplayNameFor(model => model.Media)

                                                    </span>

                                                    <span class="sale-num">

                                                        @Html.DisplayFor(model => model.Media)

                                                    </span>

                                                </li>

                                            </ul>

                                        </div>

                                    </div>

                                </div>

                                <!--end col-md-4-->

                            </div>

                            <!--end row-->

                            <div class="tabbable tabbable-custom tabbable-custom-profile">

                                <ul class="nav nav-tabs">
                                    <li class="active"><a href="#tab_1_11" data-toggle="tab">Bills</a></li>
                                </ul>

                                <div class="tab-content">

                                    <div class="tab-pane active" id="tab_1_11">

                                        <div class="portlet-body">

                                            <table class="table table-striped table-bordered table-advance table-hover">

                                                <thead>

                                                    <tr>

                                                        <th>

                                                            <i class="fa fa-briefcase"></i> Bill

                                                        </th>

                                                        <th class="hidden-xs">

                                                            <i class="fa fa-calendar"></i> Date

                                                        </th>

                                                        <th>

                                                            <i class="fa fa-money"></i> Amount

                                                        </th>

                                                        <th>

                                                        </th>

                                                    </tr>

                                                </thead>

                                                <tbody>
                                                    @foreach (Dividabill.Models.HouseholdBill bill in @Model.HouseholdBills)
                                                    {
                                                        <tr>

                                                            <td>

                                                                @Html.ActionLink("Bill " + bill.ID, "Details", "HouseholdBills", new { id = bill.ID }, null)

                                                            </td>

                                                            <td class="hidden-xs">

                                                                @bill.StartDate.ToShortDateString() - @bill.EndDate.ToShortDateString()

                                                            </td>

                                                            <td>

                                                                @bill.TotalBill

                                                                @{
                                                        var statusClass = "";
                                                        if (bill.Status == Dividabill.Models.BillStatus.Paid)
                                                        {
                                                            statusClass = "label-success";
                                                        }
                                                        else if (bill.Status == Dividabill.Models.BillStatus.Pending)
                                                        {
                                                            statusClass = "label-warning";
                                                        }
                                                        else
                                                        {
                                                            statusClass = "label-danger";
                                                        }

                                                                }
                                                                <span class="label label-sm @{@statusClass}">

                                                                    @bill.Status

                                                                </span>

                                                            </td>

                                                            <td>

                                                                @Html.ActionLink("View", "Details", "Bills", new {  id = bill.ID }, new { @class = "btn default btn-xs green-stripe" })

                                                            </td>

                                                        </tr>
                                                    }


                                                </tbody>

                                            </table>

                                        </div>

                                    </div>

                                    <!--tab-pane-->

                                </div>

                            </div>

                        </div>

                    </div>

                </div>

                <!--tab_1_2-->
                <!--end tab-pane-->
                <!--end tab-pane-->

                <div class="tab-pane" id="tab_1_6">

                    <div class="row">

                        <div class="col-md-3">

                            <ul class="ver-inline-menu tabbable margin-bottom-10">
                                @{var j = 0;}
                                @foreach (Dividabill.Models.User user in Model.Tenants)
                                {
                                    j++;
                                    <li class="">

                                        <a data-toggle="tab" href="#tab_@j">

                                            <i class="fa fa-user"></i> @user.FirstName @user.LastName

                                        </a>

                                        <span class="after">

                                        </span>

                                    </li>

                                }
                            </ul>

                        </div>

                        <div class="col-md-9">

                            <div class="tab-content">
                                @{var i = 0;
                                var active = "active";}
                                @foreach (Dividabill.Models.User user in Model.Tenants)
                                {
                                    i++;
                                    if (i > 1)
                                    {
                                        active = "";
                                    }
                                    <div id="tab_@i" class="tab-pane @active">
                                        <div id="accordion1" class="panel-group">
                                            @Html.Partial("~/Areas/Admin/Views/Shared/_UserProfile.cshtml", user)
                                        </div>

                                    </div>

                                }


                            </div>

                        </div>

                    </div>

                </div>

                <!--end tab-pane-->

            </div>

        </div>

        <!--END TABS-->

    </div>

</div>

<!-- END PAGE CONTENT-->
@section Scripts {
    @Styles.Render("~/Content/metronic-profile")
}